# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Truc Pham  
title: SRE / DevOps Engineer
email: trucpd1@amediomedia.com
# email_title: Email (Email title override)
phone:  +1234567890
# phone_title: Phone (Phone title override)
website: amediomedia.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: trucpd1rb
github_username:  trucpd1
stackoverflow_username: "00000001"
dribbble_username: trucpd1
facebook_username: trucpd1
flickr_username: trucpd1
instagram_username: trucpd1
linkedin_username: trucpd1
xing_username: trucpd1
pinterest_username: trucpd1
youtube_username: trucpd1
orcid_username: 0000-0000-0000-0000
googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)

# About Section
about_profile_image: images/profile.jpg
about_content: |
  Highly skilled SRE / DevOps Engineer with over 5 years of experience in automating infrastructure, optimizing CI/CD pipelines, and implementing monitoring solutions. Adept in cloud platforms (AWS, Azure), containerization (Docker, Kubernetes), and Infrastructure as Code (Terraform, Ansible).

content:
  - title: Skills
    layout: text
    content: |
      - **Cloud Platforms**: AWS, GCP, Azure
      - **CI/CD Tools**: Jenkins, GitLab CI, GitHub Actions
      - **Infrastructure as Code**: Terraform, Ansible, CloudFormation
      - **Containerization**: Docker, Kubernetes, Helm
      - **Scripting**: Bash, Python, Go
      - **Monitoring & Logging**: Prometheus, Grafana, ELK Stack
      - **Version Control**: Git
      - **Operating Systems**: Linux (Ubuntu, CentOS), Windows Server

  - title: Projects
    layout: list
    content:
      - layout: left
        title: Automated CI/CD Pipeline
        link: https://github.com/johndoe/cicd-pipeline
        link_text: GitHub Repo
        additional_links:
          - title: Demo Video
            icon: fab fa-youtube
            url: https://youtu.be/demo-video
        quote: >
          Automated CI/CD pipeline using Jenkins, Docker, and Kubernetes.
        description: |
          Developed and implemented a CI/CD pipeline that automated the build, test, and deployment processes. Integrated Docker for containerization and deployed microservices to a Kubernetes cluster using Helm. Reduced deployment times by 60% and minimized manual intervention.

      - layout: left
        title: Infrastructure as Code (IaC) with Terraform
        link: https://github.com/johndoe/infrastructure-as-code
        link_text: GitHub Repo
        quote: >
          Managed and automated cloud infrastructure using Terraform.
        description: |
          Created reusable Terraform modules for provisioning AWS infrastructure, including VPCs, EC2 instances, RDS databases, and S3 buckets. Enabled infrastructure consistency across environments and reduced provisioning errors.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: TechCorp Inc.
        sub_title: SRE / DevOps Engineer
        caption: June 2020 - Present
        link: https://techcorp.com
        quote: >
          Ensuring the reliability and performance of production systems.
        description: |
          - Implemented and maintained CI/CD pipelines using GitLab CI, automating the deployment of applications to Kubernetes clusters.
          - Managed AWS infrastructure using Terraform and Ansible, ensuring scalability and high availability.
          - Developed monitoring and alerting solutions using Prometheus, Grafana, and the ELK stack to improve system visibility and reduce MTTR.
          - Collaborated with development teams to implement best practices for application performance, scalability, and security.

      - layout: right
        title: CloudNet Solutions
        sub_title: DevOps Engineer
        caption: January 2018 - May 2020
        link: https://cloudnetsolutions.com
        quote: >
          Building and optimizing cloud infrastructure.
        description: |
          - Built automated deployment pipelines using Jenkins and Docker, reducing manual deployment efforts by 70%.
          - Migrated legacy applications to containerized environments, facilitating scalability and simplifying management.
          - Created custom scripts in Python and Bash to automate routine tasks, improving operational efficiency.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: State University
        sub_title: BSc Computer Science
        caption: 2014 - 2018
        quote: >
          Specialized in cloud computing and software engineering.
        description: |
          Relevant coursework included cloud architecture, software development, and network security. Worked on various projects involving containerization and cloud automation.

  - title: Certifications
    layout: list
    content:
      - layout: top-right
        title: AWS Certified Solutions Architect – Associate
        sub_title: Amazon Web Services (AWS)
        caption: Issued March 2022
        description: |
          Demonstrates knowledge and expertise in designing and deploying scalable, highly available, and fault-tolerant systems on AWS.

      - layout: top-right
        title: Certified Kubernetes Administrator (CKA)
        sub_title: The Linux Foundation
        caption: Issued August 2021
        description: |
          Validates skills required to design, deploy, and manage Kubernetes clusters in production environments.

  - title: A Little More About Me
    layout: text
    content: |
      **Interests**:
      - Open-source contributor to projects related to cloud infrastructure and DevOps.
      - Enjoy exploring new cloud technologies and tools, like serverless architecture and edge computing.

      **Skills**:
      - Strong problem-solving and analytical skills.
      - Excellent communication and collaboration with cross-functional teams.
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - trucpd1-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
